### ISSUE TITLE
Toggle button

### ISSUE THREAD

**Issue by aaronr8684** [cgiesche/streamdeck-homeassistant#110]
Is there any plan to add a toggle button with two short press actions (the toggle) and a single long press option?

Couple of use cases
- Short press - (Turn on and) Toggle between two brightness levels on lights
- Long press - Turn off

- Short - Toggle between two colors/states
- Long - Turn off

I'm sure there are a lot more examples

**Comment by cgiesche** [comment]
Hi,

thanks for your suggestion. Unfortunately, I am not planning to implement such a feature because this would lead the plugin to be "stateful" (meaning "remembering the state of the toggle"). External state changes of entities would lead to the "plugin's toggle state" and the "real" state getting out of sync. Currently, the plugin is stateless and the only "truth" is held by home assistant.

Maybe (even if I do not know how to do it exactly) it is possible to create a "virtual" entity in home assistant that would provide services for those "toggle actions".

**Comment by aaronr8684** [comment]
I'll have to look into adding the functionality within HA. I'll give you an update if I get it working.
