### ISSUE TITLE
"de.perdoctus.streamdeck.ha.entity" isn't recognized after re-install

### ISSUE THREAD

**Issue by EpicLPer** [cgiesche/streamdeck-homeassistant#133]
Heya!

Just re-installed Windows and installed the Stream Deck software again, then added this Home Assistant plugin again. However, I noticed that none of the Home Assistant keys would show up anymore and only displayed a question mark.

After manually opening all the "manifest.json" files in the profiles folder and bulk-replacing `de.perdoctus.streamdeck.ha.entity` with `de.perdoctus.streamdeck.homeassistant.entity` it worked again. I only knew about this possibility since I've done it quite a few times whenever Windows would have bigger updates and replace audio hardware IDs, so no sound effects would play anymore on a specific device.

Would it somehow be possible to add a feature that checks for both config entries and if it detects the old one to replace it with the newer version?

Thanks!

**Comment by cgiesche** [comment]
Hello,

i am currently working on new features which result in different configuration files. Because i know how painful lost button configurations can be, i added a simple versioning scheme to the configuration files.

Starting with the current version of the plugin (2.0.1 from elgato store), configurations will be automatically migrated to newer versions (as far as possible) so updates of the plugin do not destroy your existing settings.

However, `de.perdoctus.streamdeck.ha.entity` looks like you are one of the first users of my plugin (before it got to the official store?). Those old settings will unfortunately not be migrated.
