### ISSUE TITLE
Custom Icon - No text

### ISSUE THREAD

**Issue by rikardronnkvist** [cgiesche/streamdeck-homeassistant#135]
When using a custom icon on a generic button I cant have the state (or anything else) visible.

I'm trying to display a value from a sensor (car charge %) and it works with the standard icon but I would like to have a custom one.

Same config on both buttons, would like to overlay the state on the tesla-logo...
![config](https://user-images.githubusercontent.com/3245006/221112562-8e5d910a-23c2-4dc8-8785-1f0c869f1336.png)

**Comment by cgiesche** [comment]
Hi,

due to technical restrictions of the elgato API, i am not able to add text to custom icons. But there is one thing you could do as a workaround:

Clear "title" (as it already is in your case) and enable the "Custom title" option in the plugin. As the title is always working, it will be shown on top of our custom image.

![image](https://user-images.githubusercontent.com/5123180/221146676-4c94d555-245f-464c-ac9a-bc10997acd13.png)

**Comment by rikardronnkvist** [comment]
Ah... well that works at least. :)
