### ISSUE TITLE
Some entities (containing "%" character) no longer displaying after streamdeck update to 6.1.0.18521

### ISSUE THREAD

**Issue by sethmayer** [cgiesche/streamdeck-homeassistant#139]
Hi, 

All of my other entities are working but weather seems to have broken. 

Streamdeck 6.1.0.18521
Firmware 1.03.000
Home Assistant Streamdeck plugin 2.2.0
Home Assistant 2023.3.3
Frontend 20230309.0 - latest

![image](https://user-images.githubusercontent.com/5420660/226203817-ecc820b9-5bac-4313-a42e-679595816831.png)

**Comment by LuckyNils** [comment]
Same here. Weather and Phone Battery level dont work anymore. Anything else works (for example Battery Health)

**Comment by cgiesche** [comment]
Hmm, i can confirm. By why?!

**Comment by LuckyNils** [comment]
I found a pattern! All enteties/sensors that use "%" like battery levels of devices or humidity sensors also dont work. Seems to be related to the "%"-Sign

**Comment by arthurEspooner** [comment]
#114

**Comment by LuckyNils** [comment]
Well the Workaround works nicly for the Battery level with "{{state}} &#37;" in line 3, but can somebody give me a template for the weather Button/Card(What needs to be in the curly Brackets)?

**Comment by cgiesche** [comment]
For weather, you could for example use this template:
```
{{state}}
{{temperature}}{{temperature_unit}} {{humidity}}&#37;
```

In general, you can use any of the available attributes listed below the input field to customize your button:
![image](https://user-images.githubusercontent.com/5123180/226618274-9de350d2-4089-45a0-b144-6f690f96bc67.png)

**Comment by gaborbernat** [comment]
I'm running into this myself, is there any log lines I can look into?

**Comment by DarkPaladin3** [comment]
It is the % that messes it up. If the {{state}} has the number portion of the title and {{unit_of_measurement}} holds the "%" sign then you need to use the formatting below to get the "%" to show up.

{{state}} {{ unit_of_measurement | urlencode }}

If you don't have {{ unit_of_measurement }} then use,

{{state}} {{ "%" | urlencode }}

Hope that helps.

**Comment by lafaro** [comment]
I can confirm that the '%' character is maybe the issue.
Here are my cases where it doesn't work:

**Problem:**
All my humidity sensors are not displayed at the StreamDeck. Every other sensor works fine.
The issue is maybe the unit of measure, which is a "%" character and maybe needs to be escaped.

**Example:**
![grafik](https://github.com/cgiesche/streamdeck-homeassistant/assets/7762715/39af050f-1442-452a-8b7c-b8c9823bcfaa)
On the right you see the same humidity sensor as on the left, but on the left, I override the label using the "Enable custom labels" setting with the value `{{state}}`.

**Steps to reproduce (Case 1):**
1. Setup a sensor with unit_of_measurement: %
2. Try to add this sensor value with default settings to StreamDeck
3. The value is not shown

**Steps to reproduce (Case 2):**
1. Setup any sensor
2. Activate the setting "Enable custom labels" and enter `{{'%'}}` or `%`
3. The entered text "%" is not shown

**Workaround:**
Override, using cutom lablel with `{{state}}{{ "%" | urlencode }}`

**Comment by cgiesche** [comment]
Hey lafaro,

i wonder why i did not try this before: urlencoding the string before adding it to the svg image i am generating fixes the bug. Thanks for the hint. I will implement this so the workaround is no longer needed.
