### ISSUE TITLE
Question: Versioning

### ISSUE THREAD

**Issue by arthurEspooner** [cgiesche/streamdeck-homeassistant#140]
is there any requirement for the latest 2.2.0 of this plugin to use stream deck 6.x? will you be supporting both 5.x and 6.x going forward?

does elgato do anything on their side or they just pull the latest plugin version regardless of stream deck app version?

**Comment by cgiesche** [comment]
Hi @arthurEspooner 

as long as there is no need for me to require newer Stream Deck versions, I will try to stick to the current requirements. Those are:

Software: "MinimumVersion" : "4.1"
SDK: "SDKVersion": 2

Of course, I will always develop and test the plugin with the latest SD Version.

I think elgato just pulls the latest plugin version from the store. I learned it the hard way, because the "updates" always overwrite my development version ;)

**Comment by arthurEspooner** [comment]
yea, i guess they put it on you as the plugin dev to be on top of it. you seem like you are i'm not very worried!

thanks.
