### ISSUE TITLE
Entiy (custom icons) seems to be stateful?

### ISSUE THREAD

**Issue by noerK** [cgiesche/streamdeck-homeassistant#141]
Hey @cgiesche,

first off thank you for this plugin! 

I just wanted to create a reminder button for my streamdeck using **input_boolean** domain with "Entity (custom icons)". This button calls  **turn_on** service.
- Every state change in HA is reflected on the button
- Pushing the button changes the state to "on"

**BUT**
- The button toggles between the ON and OFF Version regardless of the HA state each time i press it

I looked trough some issues and read that you explicitly said: The buttons are stateless:
https://github.com/cgiesche/streamdeck-homeassistant/issues/127#issuecomment-1374911142

Thus i guess this issue is caused by a mistake i made or a stream deck update.

---
Windows 11, macOS 12
Streamdeck Software: 6.1.0 (18521)
Streamdeck Firmware: 1.00.003
Home Assistant: 2023.3.5
![Notification_Center](https://user-images.githubusercontent.com/956410/226660599-f0b7a1ca-48ec-4a9d-ada1-7abd2a70e9a4.png)

Thank you for any help in advance

**Comment by cgiesche** [comment]
Hi @noerK,

the "custom icons" button has some flaws due to how stream deck is working: As soon as you configure two icons, the button toggles between the two images as soon as you press the button (not affected by the plugin at all).
My plugin works against this "feature" by changing the image to on/off state after it got an update for the entity from home-assistant.

So, if you press the button, streamdeck automatically toggles the displayed image but if my plugin does not get any update for the entity because it's state was already "on".

I am not sure if i can fix this issue or want to keep this entity type alive at all. It has been quirky since it was invented...
