### ISSUE TITLE
Featurerequest: text wrap for title

### ISSUE THREAD

**Issue by doabigcheese** [cgiesche/streamdeck-homeassistant#148]
Hi,
is it possible to implement text wrap for longer titles? 
I have a rain announcement which have long text like "it will rain from 4:30 to 6:00"...
is there a way to display this in a readable size? 

thnx

**Comment by RonSijm** [comment]
What HASS addon/sensor are you using for the rain?

Instead of the announcement, there might be a better sensor instead of the whole text
Then you could use something like `it will rain from {{- '\n' -}} 4:30 to 6:00 {{- '\n' -}}`
or it will `{{weather}} from {{- '\n' -}} {{time}} {{- '\n' -}}` 

To have the text wrapped and centered. That's what I use for some other sensors

**Comment by doabigcheese** [comment]
Ah, was not aware that i can break it up that way.... so currently its only using an answer from a URL ([https://morgenwirdes.de/api/v3/rain.php](url) but i can try to reformat it then...
