### ISSUE TITLE
Setting relative temperature for climate

### ISSUE THREAD

**Issue by simplemal** [cgiesche/streamdeck-homeassistant#160]
Hello to everyone,
working with climate element, you can read the actual temperature in label like this 
Temp:  {{temperature}}°

also in label, you can easily add or subtract to that temperature, like {{temperature+1}} and works fine.

But seems not works when you try the same operation in Data JSON for the service "Set temperature", like this

{
  "temperature" : "{{temperature+1}}"
}

Do I have wrote something wrong in code or is it an actual limitation?

The final goal is having buttons to increase or decrease the temperature for baby steps, starting to the actual.

Thank you in advance

**Comment by cgiesche** [comment]
Hi,

this is a limitation. The data json is currently static, so no variables are evaluated.
This may change, but not soon :/

**Comment by cgiesche** [comment]
Maybe you can implement what you want by creating a script in homeassistant and call that instead of the "Set temperature" service.

**Comment by simplemal** [comment]
> Maybe you can implement what you want by creating a script in homeassistant and call that instead of the "Set temperature" service.

good idea, thanks

**Comment by cgiesche** [comment]
I tried if it works as i would expect, and at least calling a script works fine.
![image](https://github.com/cgiesche/streamdeck-homeassistant/assets/5123180/7d427b7f-64b3-42b4-8f3b-fbc63767ff66)
![image](https://github.com/cgiesche/streamdeck-homeassistant/assets/5123180/9eb59b39-5d5c-4afa-9508-0dc03bdd4b1f)

(if you see all entities in the drop down and not only scripts - that is a bug that will be fixed with the next release. Until then you have to search...)

**Comment by simplemal** [comment]
yes, I see the list, thanks
