### ISSUE TITLE
Custom Icon Button Toggle Icon is Backwards

### ISSUE THREAD

**Issue by sirjmann92** [cgiesche/streamdeck-homeassistant#163]
First, I love this plugin. Before finding it I was using Home Assistant Taskbar Menu for my Stream Deck Home Assistant needs (and still am for a few things). So thank you for making this, it's so useful!

Second, maybe it's just the way I'm configuring it, but it seems the Custom Icon feature is a bit quirky. The feature seems to allow for a "toggle" (on/off state of the custom icon). The "off" state is greyed out and the "on" state is the full color custom icon. However, the greyed out and color seems to be backwards from the state of the entity for which the button is configured. For example, the icon shows greyed out when a light is turned on (it's reading the ON state but showing the OFF status icon). I can't figure out how to reverse this without making my own custom "greyed out" icons and reversing them in the Stream Deck Home Assistant Custom Icon configuration.

Thanks again for such an awesome tool!

Any help is appreciated!

**Comment by cgiesche** [comment]
> but it seems the Custom Icon feature is a bit quirky
This is exactly how it is. I peronally dislike and never use this feature because i can not do much against it's qurikyness. 
While the "normal" buttons do always represent the state of the entity in home-assistant, the custom icon button is a mix of a stream-deck feature my plugin which do not work well togehter. If you choose icons inside the stream-deck application, the button will always toogle between these images if you click the button, regardless of the entity state. I try to work around this, but it often does not work correctly.

I just sucessfully reproduced your issue. I was not aware of the "automatically dimmed icon". It seems to be a "new" Feature that i did not notice until now. And yes, it seems like the "on" state seems to be the default in stream-deck while my plugin works the other way around.

The problem is: If i change the order now, other users who worked around this issue or defined two custom icons will face the problem.

My preferred way of fixing this issue would be removing this feature entirely. I will think about what to do ;)

**Comment by sirjmann92** [comment]
I personally like this feature. It allows me to both use a custom icon AND see the state of an object (albeit really just the state of the button). Ideally, I'd like to be able to use a custom icon (without having to create one for the inactive/off state) AND have your plugin read the state of the entity and properly report and display the appropriate icon (full color, or greyed out/dimmed). If that means dropping this feature and improving the "generic" side, then I'm fine with that. I'd still like to be able to use a custom icon and also see the state, without creating/assigning multiple icons per button. Maybe your little indicator at the top corner could be updated to be an overlay over a custom icon and provide green/blue/red statuses, something along those lines would suffice, though still not ideal (for me).

As a side note, other plugins aren't afraid to make changes that require the user to update their buttons. Most recently, the ICUE integration update required updating each iCUE button to reassign your profiles and actions, per button. Coincidentally, Corsair owns both iCUE and Elgato and they required every user to update each button without providing any convenience of automatic adjustments. Food for thought...

Thank you!
