### ISSUE TITLE
Unable to use any actions

### ISSUE THREAD

**Issue by gravok** [cgiesche/streamdeck-homeassistant#255]
I am unable to trigger actions from the Streamdeck anymore. It had worked for 2 years flawlessly with the same configuration.
I had a brief look at the release notes of HA but saw nothing which seemed related to this issue.

I am seeing access denied log entries inside HA logs every time I press a button:
> [547501012416] Error handling message: Unauthorized (unauthorized) StreamDeckUser from 10.X.Y.Z (Mozilla/5.0 ([...])

The config of an example button is: (redacted for readability):
```json
{
  "serviceShortPress": {
  "entityId": "scene.telephone_conference",
  "serviceData": "",
  "serviceId": "scene.turn_on"
}
```
Interestingly, sensors and so on are working just fine. However, no action bound to any button is working (lights, shutters, scenes, etc.)

I already tried generating another API token - however this did not change the situation at all.

Out of deperation - and in the lack of other options - I had a look at the traffic inside the websocket.
I can clearly see the request from the Plugin to HA

```json
{
    "id": 15,
    "type": "execute_script",
    "sequence": [
        {
            "service": "scene.turn_on",
            "data": {},
            "target": {
                "entity_id": [
                    "scene.telephone_conference"
                ]
            }
        }
    ]
}
```

However - I can not see the answer from HA because Wireshark fails to decompress it...

**Can you guide me to a way debugging this issue?**

Versions:
- streamdeck-homeassistant: 2.4.2 (latest version available in elgato store)
- homeassistant: 2024.2.3

**Comment by cgiesche** [comment]
Hmm, the 2.4.2 has been released on December 2023. Did it work since then?

There is an easier way to debug the plugin than wireshark:
The setup process (enable Stream-Deck debug port) is described here: https://github.com/cgiesche/streamdeck-homeassistant/issues/227#issuecomment-1875988101

After you have enabled debugging, you can connect to the plugin or the property inspector. In your case, the plugin is the relevant option:
![image](https://github.com/cgiesche/streamdeck-homeassistant/assets/5123180/b832034e-f808-4ad8-9b97-61f2151e8907)

On the following screen, you can already see some debug output (the requests you found with wireshark), maybe some home-assistant errors, too.

To see the complete communication between Home-Assistant and the plugin, navigate to the Network tab and hit refresh to see all open connections (without refresh, some may be missing):
![image](https://github.com/cgiesche/streamdeck-homeassistant/assets/5123180/b1f5e894-f4aa-4052-8208-dea5e3cb92a3)

![image](https://github.com/cgiesche/streamdeck-homeassistant/assets/5123180/7b19d177-204b-4826-9dce-473eeb38155f)
HA = Home-Assistant Websocket, SD = StreamDeck Websocket (not interesting in your case)

To see the Messages, select the "websocket" item and open the Messages tab:
![image](https://github.com/cgiesche/streamdeck-homeassistant/assets/5123180/30d8e854-f72f-44f5-b0c7-f2ea52cf6c64)
a = A request to home-assistant, b = The answer from Home-Assistant

You may want to create an empty profile with only one button to reduce message spam :)

I hope you can find a hint, what is going wrong. I hope Home-Assistant reports any useful error message. :)

**Comment by cgiesche** [comment]
Yes, that could well be. At some point in the past, I changed the way services are called. Since then, they have been wrapped in an "execute_script" call. This has the advantage that template expressions can be used in the service data object, which are then resolved on the Home Assistant side. Since execute_script essentially allows everything, it might be restricted to admin users.

I know that using admin users is not generally accepted as good practice :D - maybe (but with low prio) I will make the service-call-wrapping optional somehow.
