### ISSUE TITLE
Timer {{remaining}} not updated

### ISSUE THREAD

**Issue by sanderdatema** [cgiesche/streamdeck-homeassistant#32]
When showing a timer on a button, the {{remaining}} variable will only show the start value and won't be updated afterwards. The Idle/Active variable is, however, updated real time.

**Comment by cgiesche** [comment]
I can reproduce your issue. Unfortunatelly, it is caused by the fact, that home-assistant only sends events for state changes.
The remaining time is an additional attribute on a state, that is sent together with a state change, but not in between. So there are only two points in time, where this value gets updated: on the state change to "active" (= initial time) and on the change back to "idle" (= no value, because timer finished).

As long as home assistant does not send updates in a fixed interval for timers, i can not update the button labels. :(

(Of course, everything is possible, but this would require a custom implementation for timer entities to update their state by "polling" home assistant - which is not planned for now and would require major changes.)
