### ISSUE TITLE
Enhancement: Graphs for Sensors

### ISSUE THREAD

**Issue by shatteredeagle** [cgiesche/streamdeck-homeassistant#43]
This is already outstanding work! The only thing that would push it over the top is if we could get graphs for sensor data. Would love to see the history for my temp sensors! The HwInfo stream deck plugin is doing something super similar.

Thanks again for a killer plugin!

**Comment by cgiesche** [comment]
Wow, I just notices, that i did not answer to this. Sorry for that!

Graphs will not happen because:
- I only know the current value of an entity. There is nothing like a database, where i could store hitstoric data for the graph. Reading history data from home assistant seem to be possible but...
- ... i am not able to create graphs by programmatically painting lines in an tiny SVG graphics. I blows my mind. I am not made for fancy graphical mathematical hurdy gurdy thingies. It was already a pain to create the "icon buttons". :D
