### ISSUE TITLE
Multiple Servers

### ISSUE THREAD

**Issue by ibmlmjm** [cgiesche/streamdeck-homeassistant#47]
I would like the ability to access multiple servers on the same profile. Maybe there is a work around?

Thanx, Michael

**Comment by cgiesche** [comment]
Hi Michael,

it is currently not possible and i think there is no workaround for that. I could move the server settings from "global" to "button specific" scope but that would make configuration annoying for most of the users.
A better solution could be to add multiple server profiles and for each button, you can select, which server to use. I will keep this in mind (and this ticket open), but not yet implement it, just because i have too little time for that and have to focus on the most important issues.

**Comment by kankadev** [comment]
Need the ability to use multiple servers very bad. I use one laptop with the stream deck software and your plugin. But I move a lot between home and office. Each location has its own home assistant and stream deck.

**Comment by kankadev** [comment]
If you are interested, I would help in pair programming. I'm not familiar with this programming language but I'm an experienced developer. Maybe we can develope this feature together. I can speak German, too. :-)
