### ISSUE TITLE
Feature Request: Option to show state when using custom icon

### ISSUE THREAD

**Issue by julianrinaldi** [cgiesche/streamdeck-homeassistant#57]
When I add a custom icon to an entity, the state disappears. It also doesn't come back if I try to use a custom label like {{state}}. Is it currently possible to have a custom label or show the state when you add a custom icon? If not, it would be a great feature to have.

**Comment by cgiesche** [comment]
It is not possible to add labels to custom icons because they are not a feature by stream-deck but added by me when creating the standard images. When using user defined icons (a built in stream-deck feature), I can not add any additions to the image.

What should work, is adding the {{state}} to the title field:
![image](https://user-images.githubusercontent.com/5123180/132412697-2396047f-a176-4f64-abb4-511e87c76068.png)

**Comment by cgiesche** [comment]
PS: Please make sure to use "Entity (User defined icons for bla bla bla" if you want to use custom icons. This only works for entities with on/off states:

![image](https://user-images.githubusercontent.com/5123180/132413474-756f8b3f-ed2e-4c40-8495-308dbf9f3599.png)

This is no solution for displaying sensor data and may never be because of restrictions in the stream deck api.
