### ISSUE TITLE
Small green dot visible on icons

### ISSUE THREAD

**Issue by CorneliousJD** [cgiesche/streamdeck-homeassistant#58]
The sandard entity switch icons have a small greent dot visible in the top right corner, making them awkard to look at - not sure if there's something specific causing this or if iot's just an oversight?

Also, THANK YOU for making this. I had no idea there was even plugins available that were not in the official app.
Is there a reason this cannot be published to the offical app? I think it would increase visibility of the project and get it into more users hands.

thanks again.

**Comment by cgiesche** [comment]
Hi!

Thank you for your feedback!

The "awkward" dot is a feature :D. It indicates if a button is a single or a dual service button (green = single service, blue = dual service). You can disable the rendering of the dot by unchecking "Show visual service induicator" at the bottom of the button configuration:
![image](https://user-images.githubusercontent.com/5123180/137791592-82a7bb08-2d48-4bb9-83c0-aa3e6af4dfa7.png)

There are (at least were) two points that stopped me from publishing the plugin to the store:
1. I am not using the official "packaging tool" for creating the .sdplugin files (because it is windows only and not working in my automated build pipeline)
2. It is (was?) a more or less manual process of writing mails to elgato to publish a plugin.

Maybe i will recheck, if there is a better way today.
