### ISSUE TITLE
Group Domain Limitations

### ISSUE THREAD

**Issue by vcao** [cgiesche/streamdeck-homeassistant#62]
There are limitations on the types of service calls for groups (set, reload, or remove). Is it possible to add similar service calls like other on/off devices: turn_on, turn_off, and toggle?

**Comment by cgiesche** [comment]
Hi,

the plugin receives available services for domains from home assistant.

I had an similar request before: #33. If you define a "light group", home assistant will report "turn_on" etc. for the light-group domain (https://www.home-assistant.io/integrations/light.group/).

If you need a "generic" group (not only lights) it looks like home assistant does not provide those services, even if they should work from what i am reading in the docs (https://www.home-assistant.io/integrations/group/).

I will check, if I can add "turn_on", "turn_off" and "toggle" hardcoded for generic entity groups.

**Comment by s00500** [comment]
Hi, just stumbled into this too, I was using a different version of streamdeck plugin before and used the generic homeassistant.toggle service before there :-) (I am also using that everywhere else where I want to add this group too)
Awesome work on the plugin!

**Comment by ToBiDi0410** [comment]
_Should be fixed with this pull request, which enables the 'Homeassistant' domain for every entity:_ https://github.com/cgiesche/streamdeck-homeassistant/pull/66

This Archive includes the compiled files (if you want to use it before the pull request got merged or if it was denied):
[Compiled PR.zip](https://github.com/cgiesche/streamdeck-homeassistant/files/7780088/Compiled.PR.zip)

Place/Replace these in: %appdata%\Elgato\StreamDeck\Plugins\de.perdoctus.streamdeck.ha.sdPlugin

**Comment by cgiesche** [comment]
I just merged the PR and created a new release with this fix.
