### ISSUE TITLE
Font problem with the value of temperature

### ISSUE THREAD

**Issue by billrice** [cgiesche/streamdeck-homeassistant#72]
Hi

I am a Chinese user, so you can see that the font displayed by my temperature value is not clear, it should be a default font obtained from the system.
Is it possible to add a global font definition, or default to a font with better display effect？
thx

![image](https://user-images.githubusercontent.com/3637603/149473803-86f268e8-95c7-4e0d-848c-b5c2ee78b2f3.png)

**Comment by cgiesche** [comment]
Hi,

technically, the text that is displayed in the button is, like the icons, part of an SVG image. Because I do not know exactly, which fonts are available on the users system, i am only defining a font family ("font-family": "sans-serif").
From what i can see on your screenshot, the text is not rendered in a "sans-serif" font at all - i don't know, why.

Maybe you have not a single sans-serif font installed on your system? (hard to imagine, but well, things happen). You could try to install Roboto (https://fonts.google.com/specimen/Roboto) for testing, if the renderer will choose this font.

If this does not help, a solution could be a front picker in the settings view of the plugin, but that may take some time.

**Comment by billrice** [comment]
:(
Install Roboto doesn't show any changes.
Maybe you can  change ("font-family": "sans-serif") to  ("font-family": “Helvetica Neue”,Helvetica,Arial,”Microsoft Yahei”,sans-serif) ，packeg it and mail me,I will test and report the results.

**Comment by cgiesche** [comment]
Hi, 

i have attached a version with font-family "Roboto, Arial, Helvetica, sans-serif". I did not manage to add fonts with a space (escaping/quotes in any known combination did not work).

You will need to manually install the plugin by removing anything from Folder
`C:\Users\[XYZ]\AppData\Roaming\Elgato\StreamDeck\Plugins\de.perdoctus.streamdeck.ha.sdPlugin`
and add all files from the zip file.

Hope this will work :)

[experimental.zip](https://github.com/cgiesche/streamdeck-homeassistant/files/7869500/experimental.zip)

**Comment by billrice** [comment]
Hi

I think I solved this problem
I modified the code in plugin.1b072062.js,
"font-family":"Roboto, Arial, Helvetica, sans-serif" -->"font-family":"arial"
![$HD_{M7TCFHHBCEA)3S_T54](https://user-images.githubusercontent.com/3637603/149613668-65ad9dd7-e7b0-4926-8704-8184b97376fb.png)

the possible problem maybe
1.my system can not find sans-serif
2. snapsvg does not support multiple font settings 
:)
