### ISSUE TITLE
Call Python script service 

### ISSUE THREAD

**Issue by SnowViet** [cgiesche/streamdeck-homeassistant#91]
Hello,

How can I call a python_script when I press a button ?

Thanks

**Comment by cgiesche** [comment]
It seems this is only possible with a simple "wrapper-service" around your Python-Script:

![image](https://user-images.githubusercontent.com/5123180/159668872-cd35132d-edb7-42fe-9df5-823c95a38398.png)

After that, you can select the wrapper-script within the plugin:

![image](https://user-images.githubusercontent.com/5123180/159669254-e4b1a550-de06-43fc-9f89-deea800520ca.png)

**Comment by SnowViet** [comment]
Great thanks !
I was planning to do it with an automation, but it's better with a script.
And will you implement python_script directly in a future release ? Or is it too complicated ?

**Comment by cgiesche** [comment]
I am using a very generic approach for the plugin. That means the plugin automatically shows entities and services provided by home-assistant over their API. As python_scripts not seem to be exposed by home-assistant, they do not show up in the plugin.
It is very unlikely that i will implement some special handling for python scripts (or other integrations that do not expose entities or services) because i want to stick to the generic approach.
I think the "wrapper" is an ok-ish way to work around this :)
